django/config/urls.py
# django imports
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('rent.urls', namespace='rent')),
    url(r'^api/', include('rent.api.urls', namespace='rent_api')),
]

django/rent/api/urls.py
# django imports
from django.conf.urls import url, include
# rest framework
from rest_framework import routers
# local imports
from rent.api import views


# registering routers
router = routers.DefaultRouter()
router.register('properties', views.PropertyViewSet)


app_name='rent_api'
urlpatterns = [
    url(r'^', include(router.urls)),
]

django/rent/urls.py
# django imports
from django.conf.urls import url
# local imports
from rent import views


app_name = 'rent'
urlpatterns = [
    url(
        r'^home/$',
        views.get_homepage,
        name='homepage',
    ),
    url(
        r'^add-property/$',
        views.AddProperty.as_view(),
        name='add_property',
    ),
    url(
        r'^rented-properties/$',
        views.ListRentedProperties.as_view(),
        name='list_rented_properties',
    ),
    url(
        r'^vacant-properties/$',
        views.ListVacantProperties.as_view(),
        name='vacant_properties',
    ),
]

django/rent/models.py
from django.core.validators import MaxValueValidator
from django.conf import settings
from django.db import models


class Owner(models.Model):
    '''
    Owner.models
    '''
    # Would have been nice to make Owner an instance of User model.
    # Avoided that for simplicity sake.
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=12)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class PropertyManager(models.Manager):
    '''
    Manager for a Property model
    '''
    def get_vacant_properties(self):
        qs = self.get_queryset()
        qs = qs.filter(vacant=True)
        return qs

    def get_rented_properties(self):
        qs = self.get_queryset()
        qs = qs.filter(vacant=False)
        return qs


class Property(models.Model):
    '''
    Property.Owner.models
    '''
    HOUSING = 0
    COMMERCIAL = 1
    PROPERTY_TYPE = (
        (HOUSING, 'Housing'),
        (COMMERCIAL, 'Commercial property'),
    )

    owner = models.ForeignKey(
        Owner,
        related_name='properties',
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    address = models.CharField(max_length=70)
    city = models.CharField(max_length=50)
    property_type = models.IntegerField(choices=PROPERTY_TYPE, default=HOUSING)
    description = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rent_length = models.IntegerField(validators=[MaxValueValidator(120)])
    vacant = models.BooleanField(default=True)
    objects = PropertyManager()

    class Meta:
        ordering = ('price',)
        verbose_name_plural = ('Properties')

    def __str__(self):
        return "{} {}".format(self.address, self.city)


class RentalContract(models.Model):
    '''
    RentalContract.Property.Owner.models
    '''
    property_id = models.OneToOneField(
        Property,
        related_name='contract',
        on_delete=models.CASCADE
    )
    tenant_first_name = models.CharField(max_length=140)
    tenant_last_name = models.CharField(max_length=140)
    start_date = models.DateField(auto_now_add=True)
    end_date = models.DateField(auto_now=False)

    class Meta:
        ordering = ('end_date',)

    def __str__(self):
        return "{}, {}".format(self.property_id, self.end_date)


class RentalPayment(models.Model):
    '''
    RentalPayment.RentalContract.Property.Owner.models
    '''
    contract_id = models.OneToOneField(
        RentalContract,
        related_name='payment',
        on_delete=models.CASCADE
    )
    account_balance = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateField()

    def __str__(self):
        return "{}, ${}".format(
            self.contract_id.property_id,
            self.account_balance
        )

django/rent/forms.py
# django imports
from django import forms
from django.contrib.auth import get_user_model
# local imports
from rent.models import Property, Owner


class CreatePropertyForm(forms.ModelForm):
    '''
    Modelform for a Propety model
    '''
    owner = forms.ModelChoiceField(
        queryset=Owner.objects.all(),
        widget=forms.Select,
    )
    description = forms.CharField(
        widget=forms.Textarea,
    )

    class Meta:
        model = Property
        fields = [
            'owner', 'address', 'city', 'property_type', 'description',
            'price', 'rent_length', 'vacant'
        ]

django/rent/api/views.py
# rest framework
from rest_framework import viewsets
# rent app imports
from rent.models import Property
# local imports
from rent.api.serializers import PropertySerializer


# http://localhost:8000/api/properties/?format=json
class PropertyViewSet(viewsets.ReadOnlyModelViewSet):
    '''
    API endpoint for listing properties.
    '''
    queryset = Property.objects.all()
    serializer_class = PropertySerializer

django/rent/views.py
from datetime import date, datetime, timedelta
# django imports
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.views.generic import ListView
from django.views.generic.edit import CreateView
# local imports
from rent.forms import CreatePropertyForm
from rent.models import Property


# http://localhost:8000/home/
def get_homepage(request):
    '''
    This is root page
    '''
    return render(request, 'rent/homepage.html')


# http://localhost:8000/add-property/
class AddProperty(CreateView):
    '''
    Creates property object using CreatePropertyForm
    '''
    form_class = CreatePropertyForm
    template_name = 'rent/add_property.html'

    def get_success_url(self):
        return reverse('rent:homepage')


# http://localhost:8000/vacant-properties/
class ListVacantProperties(ListView):
    '''
    View lists all vacant Properties
    '''
    template_name = 'rent/list_vacant_properties.html'

    def get_queryset(self):
        qs = Property.objects.get_vacant_properties()
        return qs


# http://localhost:8000/rented-properties/
class ListRentedProperties(ListView):
    '''
    View lists all rented Properties
    '''
    template_name = 'rent/list_rented_properties.html'

    def get_queryset(self):
        # returns list of properties with vacant=False
        qs = Property.objects.get_rented_properties()
        return qs

    def get_context_data(self, **kwargs):
        # adds custom 30_days context variable
        # will be used in a template for changing markup style
        ctx = super().get_context_data(**kwargs)
        ctx['30_days'] = self.count_30_days_from_now()
        return ctx

    def count_30_days_from_now(self):
        # counts 30 days from current date
        today = date.today()
        return today + timedelta(days=30)

django/rent/templates/rent/add_property.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  List your Property for a Rent
{% endblock %}

{% block main %}
  <div class="py-5 text-center">
    <h1>Fill out following form to add your Property to our database</h1>
  </div>
  
  <div class="col-md-8 order-md-1">
    <form method="post">
      {% csrf_token %}
      {{ form | crispy }}
      <button class="btn btn-primary" type="submit">Submit</button>
    </form>
  </div>
  
{% endblock %}

django/rent/templates/rent/homepage.html
{% extends 'base.html' %}

{% block main %}
  <div>
    <h2>Welcome to Super Rents world's fastest growing online renting Marketplace in Housing Market.</h2>
    <p>You can list your property for a rent or find a home of your dream with us!</p>
    <br>
    
    <a href="{% url 'rent:add_property' %}">Click here if you want to list your property for a rent on SuperRents</a>
    <br>  
    <a href="{% url 'rent:list_rented_properties' %}">Click here to see all properties currently rented out</a>
    <br>
    <a href="{% url 'rent:vacant_properties' %}">Click here if you want to rent available property</a>
  </div>
{% endblock %}

django/rent/templates/rent/list_rented_properties.html
{% extends 'base.html' %}

{% block title %}
  Our Rented Properties
{% endblock %}

{% block main %}
  <h1>Our Rented Properties</h1>
  
  <div class="card-deck mb-3 text-center">
  <!-- If tag in a following code checks whether contract end date is less than expries_soon context property and applies different styles to a div based on result of an equation. This may violate "dumb template" rule but really it's an only solution worked out for me -->
  {% for property in object_list %}
    <div class="
      {% if property.contract.end_date < 30_days %}
        rent-expires-soon
      {% else %}
        property-element
      {% endif %}
      card mb-4 shadow-sm">
      <p>Address: {{ property.address }}</p>
      <p>Location: {{ property.city }}</p>
      <p>Owner's name: {{ property.owner.first_name }} {{ property.owner.last_name }}</p>
      <p>Due date: {{ property.contract.end_date }}</p>
      <p>Account balance: ${{ property.contract.payment.account_balance }}</p>
    </div>
    <br>
  {% endfor %}
  </div>
  
{% endblock %}

django/rent/templates/rent/list_vacant_properties.html
{% extends 'base.html' %}

{% block title %}
  List of vacant properties
{% endblock %}

{% block main %}
  <h1>Currently vacant Properties</h1>
  
  <div class="card-deck mb-3 text-center">
  {% for property in object_list %}
    <div class="property-element card mb-4 shadow-sm">
      <p>Address: {{ property.address }}</p>
      <p>Location: {{ property.city }}</p>
      <textarea name="" id="" cols="25" rows="8">
        {{ property.description }}
      </textarea>
      <p>Monthly fee: ${{ property.price }}</p>
      <p>Rent's period(in months): {{ property.length }}</p>
      <p>Owner's name: {{ property.owner.first_name }} {{ property.owner.last_name }}</p>
      <p>Owner's email: {{ property.owner.email }}</p>
      <p>Owner's phone number: {{ property.owner.phone_number }}</p>
    </div>
    <br>
  {% endfor %}
  </div>
  
{% endblock %}

django/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}Welcome to SuperRents{% endblock %}</title>
  <!-- Bootstrap 4.0.0 -->
  <link 
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" 
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" 
    rel="stylesheet" 
    crossorigin="anonymous">
  <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
      <a href="{% url 'rent:homepage' %}">Welcome to SuperRents</a>
    </h5>
  </div>

  <div class="container">
    {% block main %}

    {% endblock %}
  </div>
</body>
</html>